In [4]:
# Integer
1
int(1.0)

1

In [5]:
# Float
1.0
float(1)

1.0

In [6]:
# True
True

True

In [7]:
# False
False

False

In [1]:
# Equal
1 == 1

True

In [2]:
# Not equal
1 != 2

True

In [3]:
# Assign
a = 1
a

1

In [4]:
# Approximation
import sys
0.0 < sys.float_info.epsilon

True

In [5]:
# Comparison over than
2 > 1

True

In [6]:
# Comparison less than
1 < 2

True

In [7]:
# Comparison over
2 >= 1

True

In [9]:
# Comparison less
1 <= 2

True

In [10]:
# Addition
1 + 2

3

In [11]:
# Subtraction
1 - 2

-1

In [12]:
# Multiply
1 * 2

2

In [13]:
# Division
1 / 2

0.5

In [14]:
# Remainder
1 % 2

1

In [39]:
# Case
if False:
    print(0)
else:
    print(1)

1


In [18]:
# Maximum
a = [1, 2, 3, 4, 5]
max(a)

5

In [19]:
# Minimum
a = [1, 2, 3, 4, 5]
min(a)

1

In [20]:
# Absolute
abs(-1)

1

In [27]:
# Element
a = [1, 2, 3, 4, 5]
1 in a

True

In [28]:
# Part
a = [1, 2]
b = [1, 2, 3, 4, 5]
set(a) <= set(b)

True

In [29]:
# Union
a = [1, 2, 3, 4, 5]
b = [4, 5, 6, 7, 8]
list(set(a) | set(b))

[1, 2, 3, 4, 5, 6, 7, 8]

In [30]:
# Common
a = [1, 2, 3, 4, 5]
b = [4, 5, 6, 7, 8]
list(set(a) & set(b))

[4, 5]

In [31]:
# Difference
a = [1, 2, 3, 4, 5]
b = [4, 5, 6, 7, 8]
list(set(a) - set(b))

[1, 2, 3]

In [32]:
# Symmetric difference
a = [1, 2, 3, 4, 5]
b = [4, 5, 6, 7, 8]
list(set(a) ^ set(b))

[1, 2, 3, 6, 7, 8]

In [33]:
# Function
def f(x):
    return x + 1
f(1)

2

In [34]:
# Sum
a = [1, 2, 3, 4, 5]
sum(a)

15

In [35]:
# Multiplication
import math
a = [1, 2, 3, 4, 5]
math.prod(a)

120

In [36]:
# Factorial
import math
math.factorial(5)

120

In [66]:
# Exponential
10 ** 2

100

In [42]:
# Bit shift
2 << 1

4

In [47]:
# Square root
import math
math.sqrt(4)

2.0

In [49]:
# Reciprocal
2 ** -1

0.5

In [64]:
# Logarithm of 2
import math
math.log2(2)

1.0

In [65]:
# Logarithm of 10
import math
math.log10(10)

1.0

In [75]:
# Napier
import math
math.e

2.718281828459045

In [53]:
# Exponential of napier
import math
math.exp(1)

2.718281828459045

In [63]:
# Logarithm of napier
import math
math.log(2)

0.6931471805599453

In [73]:
# Exponential of 10(10^3)
1e+3

1000.0

In [74]:
# Exponential 10(10^-3)
1e-3

0.001

In [76]:
# PI
import math
math.pi

3.141592653589793

In [81]:
# Sin
import math
math.sin(math.radians(90))

1.0

In [87]:
# Radians
import math
math.radians(180)

3.141592653589793

In [89]:
# Degrees
import math
math.degrees(math.pi)

180.0

In [91]:
# Sine
import math
math.sin(math.pi/2)

1.0

In [95]:
# Cosine
import math
math.cos(math.pi)

-1.0

In [99]:
# Tangent
import math
math.tan(math.pi/4)

0.9999999999999999

In [106]:
# Arc sine
import math
math.asin(1.0)

1.5707963267948966

In [108]:
# Arc cosine
import math
math.acos(-1.0)

3.141592653589793

In [109]:
# Arc tangent
import math
math.atan(1.0)

0.7853981633974483

In [125]:
# Limit 
import sympy
sympy.var('x')
f = x ** 2 + 1
sympy.limit(f, x, 0)

1

In [127]:
# Differential
import sympy
sympy.var('x')
f = x ** 2 + 1
sympy.diff(f)

2*x

In [133]:
# Partial Differential
import sympy
sympy.var('x')
sympy.var('y')
f = x ** 2 + y ** 2 + 1
sympy.diff(f, x)

2*x

In [135]:
# Integral
import sympy
sympy.var('x')
f = x ** 2 + 1
sympy.integrate(f, (x, 0, 1))

4/3

In [1]:
# Integral
import sympy
sympy.var('x')
f = x ** 2 + 1
sympy.integrate(f, x)

x**3/3 + x

In [145]:
# Integral
import sympy
sympy.var('x')
sympy.var('y')
f = x ** 2 + y ** 2 + 1
sympy.integrate(f, x, y)

x*y**3/3 + y*(x**3/3 + x)

In [146]:
# Integral
import sympy
sympy.var('x')
sympy.var('y')
sympy.var('z')
f = x ** 2 + y ** 2 + z ** 2 + 1
sympy.integrate(f, x, y, z)

x*y*z**3/3 + z*(x**3*y/3 + x*y**3/3 + x*y)

In [147]:
# Integral
import sympy
sympy.var('x')
sympy.var('y')
f = x * y
sympy.integrate(f, x, y)

x**2*y**2/4

In [6]:
# Scalar
1.0

1.0

In [5]:
# Vector
import numpy as np
v = np.array([1.0, 1.0, 1.0])
v

array([1., 1., 1.])

In [14]:
# Vector add
import numpy as np
a = np.array([1.0, 0.0, 0.0])
b = np.array([0.0, 1.0, 0.0])
a + b

array([1., 1., 0.])

In [15]:
# Vector minus
import numpy as np
a = np.array([1.0, 0.0, 0.0])
b = np.array([0.0, 1.0, 0.0])
a - b

array([ 1., -1.,  0.])

In [16]:
# Vector multiply
import numpy as np
a = np.array([1.0, 0.0, 0.0])
b = np.array([0.0, 1.0, 0.0])
a * b

array([0., 0., 0.])

In [27]:
# Normalize
import numpy as np
v = np.array([1.0, 1.0, 1.0])
v / np.linalg.norm(v)

array([0.57735027, 0.57735027, 0.57735027])

In [19]:
# Vector division
import numpy as np
a = np.array([1.0, 0.0, 0.0])
a / 2.0

array([0.5, 0. , 0. ])

In [9]:
# Matrix
import numpy as np
M = np.matrix([[1.0, 1.0, 1.0],[1.0, 1.0, 1.0],[1.0, 1.0, 1.0]])
M

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [10]:
# L1 norm
import numpy as np
v = np.array([1.0, 1.0, 1.0])
np.linalg.norm(v, 1)

3.0

In [11]:
# L2 norm
import numpy as np
v = np.array([1.0, 1.0, 1.0])
np.linalg.norm(v, 2)

1.7320508075688772

In [13]:
# Dot product
import numpy as np
a = np.array([1.0, 0.0, 0.0])
b = np.array([0.0, 1.0, 0.0])
np.dot(a, b)

0.0

In [12]:
# Cross product
import numpy as np
a = np.array([1.0, 0.0, 0.0])
b = np.array([0.0, 1.0, 0.0])
np.cross(a, b)

array([0., 0., 1.])

In [32]:
# Inverse matrix
import numpy as np
M = np.eye(3)
np.linalg.inv(M)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# Identity matrix
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
# Determinant
import numpy as np
M = np.eye(3)
np.linalg.det(M)

1.0

In [34]:
# Transpose
import numpy as np
M = np.matrix([[1.0, 2.0, 3.0],[4.0, 5.0, 6.0],[7.0, 8.0, 9.0]])
M.T

matrix([[1., 4., 7.],
        [2., 5., 8.],
        [3., 6., 9.]])

In [52]:
# Affine matrix
import math
import numpy as np
v = np.array([1.0, 1.0, 1.0])
TM = np.matrix([[1.0, 0.0, 1.0],[0.0, 1.0, 1.0],[0.0, 0.0, 1.0]])
RM = np.matrix([[math.cos(math.radians(90)), -math.sin(math.radians(90)), 0.0],
                [math.sin(math.radians(90)), math.cos(math.radians(90)), 0.0],
                [0.0, 0.0, 1.0]])
SM = np.matrix([[2.0, 0.0, 0.0],[0.0, 2.0, 0.0],[0.0, 0.0, 1.0]])
TM @ RM @ SM @ v.T

matrix([[-1.,  3.,  1.]])

In [54]:
# Matrix add
import numpy as np
M1 = np.matrix([[1.0, 0.0, 0.0],[0.0, 1.0, 0.0],[0.0, 0.0, 1.0]])
M2 = np.matrix([[1.0, 1.0, 1.0],[1.0, 1.0, 1.0],[1.0, 1.0, 1.0]])
M1 + M2

matrix([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [55]:
# Matrix minus
import numpy as np
M1 = np.matrix([[1.0, 0.0, 0.0],[0.0, 1.0, 0.0],[0.0, 0.0, 1.0]])
M2 = np.matrix([[1.0, 1.0, 1.0],[1.0, 1.0, 1.0],[1.0, 1.0, 1.0]])
M1 - M2

matrix([[ 0., -1., -1.],
        [-1.,  0., -1.],
        [-1., -1.,  0.]])

In [56]:
# Matrix multiply
import numpy as np
M1 = np.matrix([[1.0, 0.0, 0.0],[0.0, 1.0, 0.0],[0.0, 0.0, 1.0]])
M2 = np.matrix([[1.0, 1.0, 1.0],[1.0, 1.0, 1.0],[1.0, 1.0, 1.0]])
M1 @ M2

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [58]:
# Matrix multiply
import numpy as np
M = np.matrix([[1.0, 0.0, 0.0],[0.0, 1.0, 0.0],[0.0, 0.0, 1.0]])
M * 2.0

matrix([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]])

In [59]:
# Matrix division
import numpy as np
M = np.matrix([[1.0, 0.0, 0.0],[0.0, 1.0, 0.0],[0.0, 0.0, 1.0]])
M / 2.0

matrix([[0.5, 0. , 0. ],
        [0. , 0.5, 0. ],
        [0. , 0. , 0.5]])

In [60]:
# Matrix * vector
import numpy as np
M = np.matrix([[1.0, 0.0, 0.0],[0.0, 1.0, 0.0],[0.0, 0.0, 1.0]])
v = np.array([1.0, 1.0, 1.0])
M @ v

matrix([[1., 1., 1.]])

In [63]:
# Integral
import sympy
sympy.var('x')
f = (x + sympy.sin(x)) ** 2
sympy.integrate(f, (x, 0, math.pi/2.0))

4.07732635840994